"""role-logig-redefined2

Revision ID: 2a5d7cf3c933
Revises: 5ce8f5080fda
Create Date: 2024-04-16 13:19:01.735847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2a5d7cf3c933'
down_revision: Union[str, None] = '5ce8f5080fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('id', sa.Integer(), nullable=False, primary_key=True
                                          ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_roles', 'id')
    # ### end Alembic commands ###
