"""role-logig-redefined3

Revision ID: 7b911c11feb9
Revises: 2d4bc701bda1
Create Date: 2024-04-17 10:56:12.031229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b911c11feb9'
down_revision: Union[str, None] = '2d4bc701bda1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'description')
    # ### end Alembic commands ###
