"""overlap=false

Revision ID: 9a2a57c03f77
Revises: c09b022d2edc
Create Date: 2024-04-17 19:41:52.189353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a2a57c03f77'
down_revision: Union[str, None] = 'c09b022d2edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('role', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('role', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               )
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_roles', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user_roles', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('user_roles', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('role', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               )
    op.drop_column('role', 'updated_at')
    op.drop_column('role', 'created_at')
    # ### end Alembic commands ###
